// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dohgpxyningmylyoflco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImRvaGdweHluaW5nbXlseW9mbGNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc0MTc2OTQsImV4cCI6MjA3Mjk5MzY5NH0.aIg25V_l5opuZZ5iqk210GRQf8haYnl0QiJ4Mmo0fZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});